"""
TouchDesigner Documentation Cleaner

Cleans up markdown files generated by crawl4ai to improve readability.
"""

import argparse
import os
import re
import shutil
import sys
from pathlib import Path


def clean_python_blockquotes(content: str) -> str:
    """
    Clean up blockquote formatting in Python documentation.

    The Python docs have excessive blockquotes that interfere with formatting.
    This function:
    - Removes `> ` prefix from description lines
    - Preserves code blocks but removes blockquote prefix
    - Ensures proper spacing around any remaining blockquotes
    - Adds blank lines before member/method definitions
    """
    lines = content.split('\n')
    cleaned = []
    in_code_block = False

    # Pattern for member definitions: `name` → `type` : or `name` → `type` **(Read Only)** :
    member_pattern = re.compile(r'^`[^`]+`\s*→\s*`[^`]+`.*:\s*$')

    i = 0
    while i < len(lines):
        line = lines[i]

        # Track code blocks
        if line.strip().startswith('```') or line.strip().startswith('> ```'):
            # Starting or ending a code block
            if line.strip().startswith('> ```'):
                # Remove blockquote from code fence
                line = line.replace('> ```', '```', 1)

            if not in_code_block:
                in_code_block = True
                # Ensure blank line before code block if previous line isn't blank
                if cleaned and cleaned[-1].strip() != '':
                    cleaned.append('')
            else:
                in_code_block = False

            cleaned.append(line)
            i += 1
            continue

        # Inside code block - remove blockquote prefix if present
        if in_code_block:
            if line.startswith('> '):
                line = line[2:]
            elif line.startswith('>'):
                line = line[1:]
            cleaned.append(line)
            i += 1
            continue

        # Outside code block - handle blockquotes
        if line.startswith('> '):
            # Check if this is a "real" blockquote (intentional quote) or just formatting artifact
            # In Python docs, most > lines are just descriptions, not actual quotes
            # Remove the blockquote prefix
            line = line[2:]
        elif line.strip() == '>':
            # Empty blockquote line - skip it
            i += 1
            continue

        # Add blank line before member definitions (but not if already blank or after header)
        if member_pattern.match(line):
            if cleaned and cleaned[-1].strip() != '' and not cleaned[-1].startswith('#'):
                cleaned.append('')

        cleaned.append(line)
        i += 1

    return '\n'.join(cleaned)


def remove_operator_family_footer(content: str) -> str:
    """Remove the operator family link list footer from the end of docs.

    TD wiki pages end with a section containing the operator family name
    (e.g. "CHOPs"), a "---" separator, a long line of links to every
    operator in that family, and several glossary definition lines. This
    is redundant navigation chrome that doesn't belong in the markdown.
    """
    lines = content.split('\n')
    # Known operator family names that appear as footer headers
    family_names = {'CHOPs', 'TOPs', 'SOPs', 'DATs', 'MATs', 'COMPs', 'POPs'}

    # Search from the end backwards for efficiency — the footer is always
    # at the tail of the file.
    for i in range(len(lines) - 1, 0, -1):
        stripped = lines[i].strip()
        if stripped in family_names and i + 1 < len(lines) and lines[i + 1].strip() == '---':
            # Truncate everything from this line onward
            result = '\n'.join(lines[:i]).rstrip()
            return result + '\n'

    return content


def remove_page_footer(content: str) -> str:
    """Remove trailing boilerplate after the last meaningful content.

    Class pages end with `__setstate__()` and a one-line description, followed
    by glossary definitions and other boilerplate.  Keep the `__setstate__`
    line and its description, discard everything after.  Falls back to
    truncating at a "TouchDesigner Build" line if present.
    """
    lines = content.split('\n')

    # Look for __setstate__ — keep it + next non-blank line, discard the rest
    for i, line in enumerate(lines):
        if '__setstate__' in line:
            # Find the description line (next non-blank line after __setstate__)
            desc_idx = None
            for j in range(i + 1, len(lines)):
                if lines[j].strip():
                    desc_idx = j
                    break
            if desc_idx is not None:
                result = '\n'.join(lines[:desc_idx + 1]).rstrip()
            else:
                result = '\n'.join(lines[:i + 1]).rstrip()
            return result + '\n'

    # Fallback: truncate at "TouchDesigner Build" line
    for i, line in enumerate(lines):
        if 'TouchDesigner Build' in line:
            result = '\n'.join(lines[:i]).rstrip()
            return result + '\n'

    return content


def format_parameter_bullets(content: str) -> str:
    """Convert parameter lines in Parameters sections to bullet points.

    In TD docs, parameter lines follow the pattern:
        ParamName `identifier` - description
    These are plain text lines that collapse into a single paragraph in
    markdown. This function prefixes them with '- ' to render as a proper
    list. It also removes blank lines between sub-bullet items (indented
    '* ' lines) so nested lists render correctly.
    """
    lines = content.split('\n')
    result = []
    in_params_section = False

    # Matches: "ParamName `identifier` - description"
    # Starts with a letter, has a backtick-wrapped identifier, then " - "
    param_pattern = re.compile(r'^[A-Za-z][^`]*`\w+`\s*-')
    # Matches sub-bullet items: leading whitespace then "* "
    sub_bullet_pattern = re.compile(r'^\s+\*\s')

    for i, line in enumerate(lines):
        stripped = line.strip()

        # Detect Parameters section headers
        if re.match(r'^## Parameters', stripped):
            in_params_section = True
            result.append(line)
            continue

        # Detect other section headers (exit params section)
        if stripped.startswith('## ') or stripped.startswith('# '):
            in_params_section = False
            result.append(line)
            continue

        if in_params_section:
            # Convert top-level parameter lines to bullet points
            if param_pattern.match(stripped):
                result.append(f'- {stripped}')
                continue

            # Remove blank lines that precede a sub-bullet or another param
            # so nested lists stay contiguous
            if stripped == '' and i + 1 < len(lines):
                next_line = lines[i + 1]
                next_stripped = next_line.strip()
                if sub_bullet_pattern.match(next_line) or param_pattern.match(next_stripped):
                    continue

        result.append(line)

    return '\n'.join(result)


def compact_bullet_lists(content: str) -> str:
    """Remove blank lines between consecutive bullet/sub-bullet list items.

    Crawl4AI often inserts blank lines between list items (``- `` or ``* ``),
    which causes markdown renderers to treat them as separate lists or add
    unwanted paragraph spacing.  This function removes blank lines that sit
    between two list item lines, keeping bullet lists contiguous.

    Uses regex substitution so it is unaffected by stray/unclosed code fences
    in the document.
    """
    # Pattern: a bullet line, then one or more blank lines, then another bullet line.
    # Bullet lines start with optional whitespace then a list marker (-, *, +, or 1.)
    bullet_line = r'([ \t]*[-*+]\s.+|[ \t]*\d+\.\s.+)'
    blank_between = re.compile(bullet_line + r'\n(?:\s*\n)+(' + r'[ \t]*[-*+]\s)')
    # Repeatedly apply until stable (handles long chains of items)
    prev = None
    while prev != content:
        prev = content
        content = blank_between.sub(r'\1\n\2', content)
    return content


def convert_self_anchor_links(content: str) -> str:
    """Convert absolute anchor links to relative when they point to the same page.

    TOC entries and self-references use absolute URLs like:
        [1 Members](https://docs.derivative.ca/BloomTOP_Class#Members)
    This converts them to relative anchors so they work in local markdown:
        [1 Members](#Members)

    Only links whose URL page name matches the file's frontmatter title are
    converted; cross-page anchor links are left unchanged.
    """
    # Extract title from YAML frontmatter
    if not content.startswith('---'):
        return content
    parts = content.split('---', 2)
    if len(parts) < 3:
        return content
    title = ''
    for line in parts[1].strip().split('\n'):
        if line.startswith('title:'):
            title = line[len('title:'):].strip()
            break
    if not title:
        return content

    # Replace [text](https://docs.derivative.ca/Title#fragment "optional") -> [text](#fragment)
    pattern = (
        r'\[([^\]]+)\]\(https://docs\.derivative\.ca/'
        + re.escape(title)
        + r'#([^)\s"]+)(?:\s+"[^"]*")?\)'
    )
    return re.sub(pattern, r'[\1](#\2)', content)


def ensure_blockquote_spacing(content: str) -> str:
    """Ensure blank lines before and after blockquote lines.

    Lines starting with > should have blank lines around them for proper
    markdown rendering.  Consecutive blockquote lines are treated as a single
    block (spacing is only added before the first and after the last).
    Code-fenced regions are left untouched.
    """
    lines = content.split('\n')
    result = []
    in_code_block = False
    frontmatter_count = 0

    for line in lines:
        stripped = line.strip()

        # Track frontmatter — pass through unchanged
        if stripped == '---':
            frontmatter_count += 1
        if frontmatter_count < 2:
            result.append(line)
            continue

        # Track code blocks — pass through unchanged
        if stripped.startswith('```'):
            in_code_block = not in_code_block
            result.append(line)
            continue
        if in_code_block:
            result.append(line)
            continue

        if stripped.startswith('>'):
            # Blank line before, unless previous line is blank or also a blockquote
            if result and result[-1].strip() != '' and not result[-1].strip().startswith('>'):
                result.append('')
            result.append(line)
        else:
            # Blank line after a blockquote block, unless current line is blank
            if result and result[-1].strip().startswith('>') and stripped != '':
                result.append('')
            result.append(line)

    return '\n'.join(result)


def _is_plain_text(line: str) -> bool:
    """Return True if *line* looks like a plain prose paragraph line.

    Returns False for blank lines, markdown structural elements (headers,
    list items, code fences, blockquotes, images, tables, horizontal rules),
    and indented lines (which may be continued list content).
    """
    stripped = line.strip()
    if not stripped:
        return False
    # Headers
    if stripped.startswith('#'):
        return False
    # List items (unordered and ordered) and sub-bullets
    if re.match(r'^[-*+]\s', stripped) or re.match(r'^\d+\.\s', stripped):
        return False
    # Code fences
    if stripped.startswith('```'):
        return False
    # Blockquotes
    if stripped.startswith('>'):
        return False
    # Images / image-links standing alone
    if stripped.startswith('[![') or stripped.startswith('!['):
        return False
    # Table rows (contain | pipe separators) and table separator lines
    if '|' in stripped:
        return False
    # Horizontal rules
    if re.match(r'^[-*_]{3,}$', stripped):
        return False
    # Indented content (continuation of list items, etc.)
    if line.startswith('  '):
        return False
    return True


def separate_paragraphs(content: str) -> str:
    """Insert blank lines between consecutive plain-text paragraph lines.

    Crawl4AI collapses HTML ``<p>`` boundaries into adjacent lines with no
    blank line in between.  Markdown renderers then treat them as a single
    paragraph.  This function detects runs of consecutive plain prose lines
    (ignoring headers, lists, code, blockquotes, tables, etc.) and inserts a
    blank line between each pair.

    Code-fenced regions and frontmatter are left untouched.
    """
    lines = content.split('\n')
    result: list[str] = []
    in_code_block = False
    frontmatter_count = 0

    for line in lines:
        stripped = line.strip()

        # Track frontmatter — pass through unchanged
        if stripped == '---':
            frontmatter_count += 1
        if frontmatter_count < 2:
            result.append(line)
            continue

        # Track code blocks — pass through unchanged
        if stripped.startswith('```'):
            in_code_block = not in_code_block
            result.append(line)
            continue
        if in_code_block:
            result.append(line)
            continue

        # If the previous line was plain text and this line is also plain
        # text, insert a blank line so markdown sees them as separate
        # paragraphs.
        if result and _is_plain_text(result[-1]) and _is_plain_text(line):
            result.append('')

        result.append(line)

    return '\n'.join(result)


def ensure_header_spacing(content: str) -> str:
    """Ensure blank lines before and after markdown header lines.

    Headers (lines starting with ``#``) should have a blank line above and
    below them for proper rendering and readability.  Frontmatter delimiters
    and code-fenced regions are left untouched.
    """
    lines = content.split('\n')
    result: list[str] = []
    in_code_block = False
    frontmatter_count = 0

    for i, line in enumerate(lines):
        stripped = line.strip()

        # Track frontmatter — pass through unchanged
        if stripped == '---':
            frontmatter_count += 1
        if frontmatter_count < 2:
            result.append(line)
            continue

        # Track code blocks — pass through unchanged
        if stripped.startswith('```'):
            in_code_block = not in_code_block
            result.append(line)
            continue
        if in_code_block:
            result.append(line)
            continue

        is_header = stripped.startswith('#')

        # Ensure blank line before header
        if is_header and result and result[-1].strip() != '':
            result.append('')

        result.append(line)

        # Ensure blank line after header: peek ahead at next non-appended
        # line.  We insert a blank after the header if the next source line
        # is non-empty and not itself a header.  The blank-line contraction
        # step later will collapse any duplicates.
        if is_header and i + 1 < len(lines):
            next_stripped = lines[i + 1].strip()
            if next_stripped and not next_stripped.startswith('#'):
                result.append('')

    return '\n'.join(result)


def clean_code_block_blanks(content: str) -> str:
    """Remove blank lines immediately before closing code fences.

    Crawl4AI often inserts a blank line before the closing ````` ```,
    producing code blocks with trailing whitespace that looks untidy.
    """
    lines = content.split('\n')
    result: list[str] = []
    in_code_block = False

    for line in lines:
        stripped = line.strip()

        if stripped.startswith('```'):
            if in_code_block:
                # Closing fence — remove trailing blank lines
                while result and result[-1].strip() == '':
                    result.pop()
            in_code_block = not in_code_block

        result.append(line)

    return '\n'.join(result)


def compact_tables(content: str) -> str:
    """Remove blank lines inside markdown tables.

    Markdown tables break if there are blank lines between rows.  This
    function finds table regions (identified by a separator row matching
    ``---|---``) and removes any blank lines between table rows.
    """
    lines = content.split('\n')

    # First pass: find separator row indices
    sep_indices: set[int] = set()
    for i, line in enumerate(lines):
        stripped = line.strip()
        # Table separator: consists of |, -, :, and spaces only
        if stripped and '|' in stripped and re.match(r'^[\s|:\-]+$', stripped):
            sep_indices.add(i)

    if not sep_indices:
        return content

    # Second pass: for each separator, find the full table extent and
    # collect indices of blank lines within it.
    blank_to_remove: set[int] = set()

    for sep_idx in sep_indices:
        # Walk upward from separator to find start of table
        top = sep_idx
        while top > 0:
            prev = top - 1
            if lines[prev].strip() == '':
                # Check if there is a table row above the blank line
                above = prev - 1
                if above >= 0 and '|' in lines[above]:
                    blank_to_remove.add(prev)
                    top = above
                else:
                    break
            elif '|' in lines[prev]:
                top = prev
            else:
                break

        # Walk downward from separator to find end of table
        bottom = sep_idx
        while bottom < len(lines) - 1:
            nxt = bottom + 1
            if lines[nxt].strip() == '':
                # Check if there is a table row below the blank line
                below = nxt + 1
                if below < len(lines) and '|' in lines[below]:
                    blank_to_remove.add(nxt)
                    bottom = below
                else:
                    break
            elif '|' in lines[nxt]:
                bottom = nxt
            else:
                break

    if not blank_to_remove:
        return content

    return '\n'.join(line for i, line in enumerate(lines) if i not in blank_to_remove)


def clean_td_markdown(content: str, is_python_doc: bool = False) -> str:
    """Clean TouchDesigner documentation markdown."""
    lines = content.split('\n')
    cleaned = []
    in_frontmatter = False
    frontmatter_count = 0
    skip_toc = False

    for line in lines:
        # Track frontmatter
        if line.strip() == '---':
            frontmatter_count += 1
            in_frontmatter = frontmatter_count == 1
            cleaned.append(line)
            continue

        # Preserve frontmatter as-is
        if frontmatter_count < 2:
            cleaned.append(line)
            continue

        # Remove 'From Derivative' line
        if line.strip() == 'From Derivative':
            continue

        # Remove wikieditor metadata lines
        if 'wikieditor' in line.lower():
            continue

        # Remove 'Jump to navigation/search' links
        if 'Jump to navigation' in line or 'Jump to search' in line:
            continue

        # Strip "Experimental:" prefix from headers and content
        line = re.sub(r'Experimental:', '', line)

        # Remove edit links [[edit](...)]
        line = re.sub(r'\s*\[\[edit\]\([^)]+\)\]', '', line)

        # Remove standalone [edit](...) links
        line = re.sub(r'\s*\[edit\]\(https://docs\.derivative\.ca/index\.php[^)]+\)', '', line)

        # Remove empty ## headers (MediaWiki artifact)
        if line.strip() == '##':
            continue

        # Strip >> (double blockquote) prefix — formatting artifact
        if line.startswith('>>'):
            line = re.sub(r'^>>\s?', '', line)

        # Skip Contents/TOC section
        if line.strip() == '## Contents':
            skip_toc = True
            continue
        if skip_toc:
            # TOC lines are indented lists with [number
            if re.match(r'\s*\*\s*\[\d+', line) or line.strip() == '':
                if line.strip() == '':
                    skip_toc = False  # Empty line ends TOC
                continue
            else:
                skip_toc = False

        # Clean up Python icon + class links: [![PythonIcon...](...)[Class](...) -> [Class](...)
        line = re.sub(r'\[!\[PythonIcon\.png\]\([^)]+\)\]\([^)]+\)', '', line)

        # Fix section headers that lost their ## prefix
        # Common patterns: "Summary", "Parameters - X Page", "Operator Inputs", etc.
        header_patterns = [
            r'^(Summary)$',
            r'^(Parameters\s*-\s*.+Page)$',
            r'^(Operator Inputs)$',
            r'^(Operator Outputs)$',
            r'^(Info CHOP Channels)$',
            r'^(Common .+ Info Channels)$',
            r'^(Methods)$',
            r'^(Members)$',
            r'^(Special Members)$',
            r'^(See Also)$',
            r'^(Examples?)$',
            r'^(Notes?)$',
            r'^(Usage)$',
        ]

        stripped = line.strip()
        for pattern in header_patterns:
            if re.match(pattern, stripped, re.IGNORECASE):
                line = f'## {stripped}'
                break

        cleaned.append(line)

    # Join and clean up
    result = '\n'.join(cleaned)

    # Apply Python-specific cleaning if this is a Python doc
    if is_python_doc:
        result = clean_python_blockquotes(result)

    # Convert same-page absolute anchor links to relative
    result = convert_self_anchor_links(result)

    # Ensure blank lines around blockquote lines
    result = ensure_blockquote_spacing(result)

    # Ensure blank lines before and after headers
    result = ensure_header_spacing(result)

    # Separate consecutive plain-text lines into distinct paragraphs
    result = separate_paragraphs(result)

    # Remove trailing blank lines inside code blocks
    result = clean_code_block_blanks(result)

    # Remove stray blank lines inside markdown tables (which break rendering)
    result = compact_tables(result)

    # Remove operator family link list footer (CHOPs, TOPs, etc.)
    result = remove_operator_family_footer(result)

    # Remove trailing boilerplate (glossary defs, build info, etc.)
    result = remove_page_footer(result)

    # Format parameter sections with proper bullet points
    result = format_parameter_bullets(result)

    # Remove blank lines between consecutive bullet list items
    result = compact_bullet_lists(result)

    # Contract multiple empty lines to max 2
    result = re.sub(r'\n{3,}', '\n\n', result)

    # Remove trailing whitespace from lines
    result = '\n'.join(line.rstrip() for line in result.split('\n'))

    return result.strip() + '\n'


def build_url_to_file_map(docs_dir: Path) -> dict[str, Path]:
    """Build a mapping from URL page names to local file paths.

    Scans all markdown files for their ``url:`` frontmatter field and returns
    a dict mapping the page name portion of the URL (e.g. ``ScurveCHOP_Class``)
    to the file's path relative to *docs_dir*.
    """
    url_to_file: dict[str, Path] = {}
    for md in docs_dir.rglob('*.md'):
        try:
            # Only read the first few lines for the frontmatter
            with open(md, 'r', encoding='utf-8') as f:
                head = f.read(512)
        except Exception:
            continue
        m = re.search(r'^url:\s*https?://docs\.derivative\.ca/(.+)$', head, re.MULTILINE)
        if m:
            url_to_file[m.group(1)] = md.relative_to(docs_dir)
    return url_to_file


def localize_links(content: str, file_path: Path, docs_dir: Path,
                   url_map: dict[str, Path]) -> str:
    """Convert docs.derivative.ca links to relative local file paths.

    For each markdown link pointing to ``https://docs.derivative.ca/PageName``,
    if *PageName* exists in *url_map*, the URL is replaced with a relative
    path from the current file to the target file.  Fragment anchors
    (``#section``) are preserved.  Links to pages we don't have locally are
    left as absolute URLs.
    """
    file_rel = file_path.relative_to(docs_dir)
    file_dir = file_rel.parent  # e.g. Path('CHOPs')

    def _replace_link(m: re.Match) -> str:
        prefix = m.group(1)       # "[text](" or bare start
        page_name = m.group(2)    # e.g. "ScurveCHOP_Class"
        fragment = m.group(3) or ""  # e.g. "#Members" or ""
        suffix = m.group(4)       # closing paren/quote/space or title text

        if page_name not in url_map:
            return m.group(0)  # leave unresolvable links unchanged

        target_path = url_map[page_name]
        # Compute relative path from current file's directory to target
        try:
            rel = Path(os.path.relpath(target_path, file_dir))
        except ValueError:
            return m.group(0)

        # Use forward slashes for markdown compatibility
        rel_str = rel.as_posix()

        return f'{prefix}{rel_str}{fragment}{suffix}'

    # Match markdown links: [text](https://docs.derivative.ca/PageName#frag "title")
    # Also match bare URLs not inside markdown link syntax
    pattern = re.compile(
        r'(\[(?:[^\]]*)\]\()'                        # "[text]("
        r'https://docs\.derivative\.ca/'
        r'([A-Za-z0-9_:%.]+?)'                       # page name
        r'(#[^)\s"]*)?'                               # optional #fragment
        r'(\s+"[^"]*"\)|\))'                          # optional " title") or just ")"
    )

    return pattern.sub(_replace_link, content)


def clean_file(file_path: Path, dry_run: bool = False) -> bool:
    """Clean a single markdown file."""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            original = f.read()

        # Detect if this is a Python documentation file
        is_python_doc = 'Python' in str(file_path) or '_Class.md' in str(file_path)

        cleaned = clean_td_markdown(original, is_python_doc=is_python_doc)

        if cleaned != original:
            if not dry_run:
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(cleaned)
            return True
        return False
    except Exception as e:
        print(f"  Error processing {file_path}: {e}", file=sys.stderr)
        return False


def relocate_general_files(docs_dir: Path, dry_run: bool = False) -> int:
    """Move general/meta wiki pages into a shared General directory.

    Pages like TouchDesigner_Glossary.md and Tutorials.md appear in
    multiple category directories. This consolidates them into a single
    General/ directory and removes duplicates.
    """
    # Kept in sync with GENERAL_PAGE_FILENAMES in crawler.py.
    # Duplicated here to avoid importing crawler (which pulls in crawl4ai).
    general_filenames = {
        "TouchDesigner_Glossary.md",
        "TouchDesigner_Python_Classes.md",
        "Tutorials.md",
        "Derivative_About.md",
        "Frequently_Asked_Questions.md",
        "Interoperability.md",
        "Learn_TouchDesigner.md",
        "Main_Page.md",
        "Release_Notes.md",
        "Python.md",
        "Operator.md",
    }

    general_dir = docs_dir / "General"
    moved = 0

    for md_file in sorted(docs_dir.rglob("*.md")):
        if md_file.name not in general_filenames:
            continue
        # Skip files already in General/
        if md_file.parent == general_dir:
            continue

        target = general_dir / md_file.name
        action = "Would move" if dry_run else "Moved"

        if target.exists():
            # Duplicate — just delete it
            if not dry_run:
                md_file.unlink()
            print(f"  Removed duplicate: {md_file.relative_to(docs_dir)}")
        else:
            if not dry_run:
                general_dir.mkdir(parents=True, exist_ok=True)
                shutil.move(str(md_file), str(target))
            print(f"  {action}: {md_file.relative_to(docs_dir)} -> General/{md_file.name}")
            moved += 1

    return moved


def clean_directory(docs_dir: Path, dry_run: bool = False) -> tuple[int, int]:
    """Clean all markdown files in the documentation directory."""
    # First, relocate general pages to the General directory
    relocated = relocate_general_files(docs_dir, dry_run)
    if relocated:
        print()

    # Build URL-to-file map for link localization
    url_map = build_url_to_file_map(docs_dir)

    cleaned_count = 0
    total_count = 0

    for md_file in docs_dir.rglob('*.md'):
        total_count += 1

        # Standard cleaning
        changed = clean_file(md_file, dry_run)

        # Link localization (separate pass since it needs cross-file info)
        try:
            content = md_file.read_text(encoding='utf-8')
            localized = localize_links(content, md_file, docs_dir, url_map)
            if localized != content:
                if not dry_run:
                    md_file.write_text(localized, encoding='utf-8')
                changed = True
        except Exception as e:
            print(f"  Error localizing links in {md_file}: {e}", file=sys.stderr)

        if changed:
            cleaned_count += 1
            action = "Would clean" if dry_run else "Cleaned"
            print(f"  {action}: {md_file.relative_to(docs_dir)}")

    return cleaned_count, total_count


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Clean TouchDesigner documentation markdown files"
    )
    parser.add_argument(
        "-d", "--docs-dir",
        type=Path,
        default=Path("td_docs"),
        help="Documentation directory (default: td_docs)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be cleaned without making changes"
    )
    parser.add_argument(
        "-f", "--file",
        type=Path,
        help="Clean a single file instead of the whole directory"
    )

    args = parser.parse_args()

    print("TouchDesigner Documentation Cleaner")
    print("=" * 40)

    if args.file:
        if clean_file(args.file, args.dry_run):
            action = "Would clean" if args.dry_run else "Cleaned"
            print(f"{action}: {args.file}")
        else:
            print(f"No changes needed: {args.file}")
    else:
        if not args.docs_dir.exists():
            print(f"Error: Directory not found: {args.docs_dir}", file=sys.stderr)
            sys.exit(1)

        print(f"Directory: {args.docs_dir}")
        if args.dry_run:
            print("Mode: DRY RUN (no changes will be made)")
        print()

        cleaned, total = clean_directory(args.docs_dir, args.dry_run)

        print()
        print("=" * 40)
        action = "Would clean" if args.dry_run else "Cleaned"
        print(f"{action} {cleaned} of {total} files")


if __name__ == "__main__":
    main()
